services:
    redis:
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
    app:
        build: ./
        ports:
            - 5001:5000
        depends_on:
            - redis
        env_file: ".env"
        command: python main.py

    celery_worker:
        build: ./
        depends_on:
            - redis
            - app
        env_file: ".env"
        command: celery -A celery_app worker --loglevel=info

    flower:
        image: mher/flower
        ports:
            - 5555:5555
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
            - celery_worker