version: '3.8'

services:
    redis:
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
    app:
        build: ./
        ports:
            - 5001:5000
        depends_on:
            - redis
        env_file: ".env"
