version: '3.8'
networks:
  app:
services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
  app:
    build: ./
    command: python3 main.py
    ports:
      - 5000:5000
    depends_on:
      - redis
    
    
